---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-demo-project
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://gitlab.com/sandeepputta1/cicd-argocd"
    targetRevision: HEAD
    path: k8s
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - createNamespace=true
